# Generated by Django 4.2.7 on 2023-11-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_follower_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
