# Generated by Django 4.2.7 on 2023-11-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_comment_user_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_like',
        ),
    ]
